/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  BedroomNftInterface,
  BedroomNftInterfaceInterface,
} from "../BedroomNftInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "tokenIdToNftOwnership",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "designId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "level",
            type: "uint256",
          },
          {
            internalType: "enum Category",
            name: "category",
            type: "uint8",
          },
        ],
        internalType: "struct NftOwnership",
        name: "_struct",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class BedroomNftInterface__factory {
  static readonly abi = _abi;
  static createInterface(): BedroomNftInterfaceInterface {
    return new utils.Interface(_abi) as BedroomNftInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BedroomNftInterface {
    return new Contract(address, _abi, signerOrProvider) as BedroomNftInterface;
  }
}
