/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IReward, IRewardInterface } from "../IReward";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "CloseStream",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "int96",
        name: "flowRate",
        type: "int96",
      },
    ],
    name: "OpenUpdateStream",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_receiver",
        type: "address",
      },
    ],
    name: "closeStream",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_rewardIndex",
        type: "uint256",
      },
    ],
    name: "createUpdateStream",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum IBedroomNft.Category",
        name: "_category",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "_indexReward",
        type: "uint256",
      },
      {
        internalType: "int96",
        name: "_flowRate",
        type: "int96",
      },
    ],
    name: "setRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ISuperToken",
        name: "_superToken",
        type: "address",
      },
    ],
    name: "setSuperToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IReward__factory {
  static readonly abi = _abi;
  static createInterface(): IRewardInterface {
    return new utils.Interface(_abi) as IRewardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReward {
    return new Contract(address, _abi, signerOrProvider) as IReward;
  }
}
