/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IRewardInterface extends ethers.utils.Interface {
  functions: {
    "closeStream(address)": FunctionFragment;
    "createUpdateStream(address,uint256,uint256)": FunctionFragment;
    "setRewards(uint8,uint256,int96)": FunctionFragment;
    "setSuperToken(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "closeStream", values: [string]): string;
  encodeFunctionData(
    functionFragment: "createUpdateStream",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewards",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSuperToken",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "closeStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createUpdateStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSuperToken",
    data: BytesLike
  ): Result;

  events: {
    "CloseStream(address)": EventFragment;
    "OpenUpdateStream(address,int96)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CloseStream"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OpenUpdateStream"): EventFragment;
}

export type CloseStreamEvent = TypedEvent<[string] & { receiver: string }>;

export type OpenUpdateStreamEvent = TypedEvent<
  [string, BigNumber] & { receiver: string; flowRate: BigNumber }
>;

export class IReward extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IRewardInterface;

  functions: {
    closeStream(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createUpdateStream(
      _receiver: string,
      _tokenId: BigNumberish,
      _rewardIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRewards(
      _category: BigNumberish,
      _indexReward: BigNumberish,
      _flowRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSuperToken(
      _superToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  closeStream(
    _receiver: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createUpdateStream(
    _receiver: string,
    _tokenId: BigNumberish,
    _rewardIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRewards(
    _category: BigNumberish,
    _indexReward: BigNumberish,
    _flowRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSuperToken(
    _superToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    closeStream(_receiver: string, overrides?: CallOverrides): Promise<void>;

    createUpdateStream(
      _receiver: string,
      _tokenId: BigNumberish,
      _rewardIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setRewards(
      _category: BigNumberish,
      _indexReward: BigNumberish,
      _flowRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setSuperToken(
      _superToken: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CloseStream(address)"(
      receiver?: null
    ): TypedEventFilter<[string], { receiver: string }>;

    CloseStream(
      receiver?: null
    ): TypedEventFilter<[string], { receiver: string }>;

    "OpenUpdateStream(address,int96)"(
      receiver?: null,
      flowRate?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { receiver: string; flowRate: BigNumber }
    >;

    OpenUpdateStream(
      receiver?: null,
      flowRate?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { receiver: string; flowRate: BigNumber }
    >;
  };

  estimateGas: {
    closeStream(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createUpdateStream(
      _receiver: string,
      _tokenId: BigNumberish,
      _rewardIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRewards(
      _category: BigNumberish,
      _indexReward: BigNumberish,
      _flowRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSuperToken(
      _superToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    closeStream(
      _receiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createUpdateStream(
      _receiver: string,
      _tokenId: BigNumberish,
      _rewardIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRewards(
      _category: BigNumberish,
      _indexReward: BigNumberish,
      _flowRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSuperToken(
      _superToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
