/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ISuperAppInterface extends ethers.utils.Interface {
  functions: {
    "afterAgreementCreated(address,address,bytes32,bytes,bytes,bytes)": FunctionFragment;
    "afterAgreementTerminated(address,address,bytes32,bytes,bytes,bytes)": FunctionFragment;
    "afterAgreementUpdated(address,address,bytes32,bytes,bytes,bytes)": FunctionFragment;
    "beforeAgreementCreated(address,address,bytes32,bytes,bytes)": FunctionFragment;
    "beforeAgreementTerminated(address,address,bytes32,bytes,bytes)": FunctionFragment;
    "beforeAgreementUpdated(address,address,bytes32,bytes,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "afterAgreementCreated",
    values: [string, string, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "afterAgreementTerminated",
    values: [string, string, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "afterAgreementUpdated",
    values: [string, string, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeAgreementCreated",
    values: [string, string, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeAgreementTerminated",
    values: [string, string, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeAgreementUpdated",
    values: [string, string, BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "afterAgreementCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterAgreementTerminated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterAgreementUpdated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeAgreementCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeAgreementTerminated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeAgreementUpdated",
    data: BytesLike
  ): Result;

  events: {};
}

export class ISuperApp extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ISuperAppInterface;

  functions: {
    afterAgreementCreated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      cbdata: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    afterAgreementTerminated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      cbdata: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    afterAgreementUpdated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      cbdata: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    beforeAgreementCreated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { cbdata: string }>;

    beforeAgreementTerminated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { cbdata: string }>;

    beforeAgreementUpdated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { cbdata: string }>;
  };

  afterAgreementCreated(
    superToken: string,
    agreementClass: string,
    agreementId: BytesLike,
    agreementData: BytesLike,
    cbdata: BytesLike,
    ctx: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  afterAgreementTerminated(
    superToken: string,
    agreementClass: string,
    agreementId: BytesLike,
    agreementData: BytesLike,
    cbdata: BytesLike,
    ctx: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  afterAgreementUpdated(
    superToken: string,
    agreementClass: string,
    agreementId: BytesLike,
    agreementData: BytesLike,
    cbdata: BytesLike,
    ctx: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  beforeAgreementCreated(
    superToken: string,
    agreementClass: string,
    agreementId: BytesLike,
    agreementData: BytesLike,
    ctx: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  beforeAgreementTerminated(
    superToken: string,
    agreementClass: string,
    agreementId: BytesLike,
    agreementData: BytesLike,
    ctx: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  beforeAgreementUpdated(
    superToken: string,
    agreementClass: string,
    agreementId: BytesLike,
    agreementData: BytesLike,
    ctx: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    afterAgreementCreated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      cbdata: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    afterAgreementTerminated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      cbdata: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    afterAgreementUpdated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      cbdata: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    beforeAgreementCreated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    beforeAgreementTerminated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    beforeAgreementUpdated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    afterAgreementCreated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      cbdata: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    afterAgreementTerminated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      cbdata: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    afterAgreementUpdated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      cbdata: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    beforeAgreementCreated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    beforeAgreementTerminated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    beforeAgreementUpdated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    afterAgreementCreated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      cbdata: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    afterAgreementTerminated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      cbdata: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    afterAgreementUpdated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      cbdata: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    beforeAgreementCreated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    beforeAgreementTerminated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    beforeAgreementUpdated(
      superToken: string,
      agreementClass: string,
      agreementId: BytesLike,
      agreementData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
